# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b93b8fd2b04084713c8389f091e107a25b90f48b72d7ac86ce5289645a32ebea0d3b224c89694d587c65a168da3573d5fcf9b7098df9606c9d7e030de7073396

test:
  secret_key_base: 28b8ad3b70361582fd144c6f9af9825bc19b45dc79d2b27229bd1593761fc5d678c52adb9b23ba7b8fca2207b2ea2d186c7af04439b0c38dd7816c8263c4815d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
